name: Java CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [8, 8.0.192, 9, 10, 11, 11.0.3, 12, 13, 13.0.4, 14, 15, 16, 17, 17.0.6, 18, 19, 20, 20-EA]
      fail-fast: false
      max-parallel: 6           
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Test with Maven
      run: mvn test -B --file pom.xml

  test-zing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8.0.252, 8, 11.0.7, 11, 17, 17.0.6]
      fail-fast: false
      max-parallel: 6           
    name: Test Zing JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: zing-actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Test with Maven
      run: mvn test -B --file pom.xml

